# Generated by Django 4.0.7 on 2023-09-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
